package com.securevault.audit.model;

public enum AuditAction {
    USER_REGISTERED,
    USER_LOGIN,
    USER_LOGIN_FAILED,
    USER_LOGOUT,
    TOKEN_REFRESHED,
    TOTP_ENABLED,
    TOTP_DISABLED,
    TOTP_VERIFIED,

    SECRET_CREATED,
    SECRET_READ,
    SECRET_UPDATED,
    SECRET_DELETED,

    FOLDER_CREATED,
    FOLDER_UPDATED,
    FOLDER_DELETED,

    SECRET_SHARED,
    SHARE_REVOKED,
    SHARE_PERMISSION_CHANGED
}
